### PR TITLE
Installed title hiding selection fix and simplification

### PR DESCRIPTION
**Pull request by TheLogicMaster**
Fixed the title selection bug and extracted the version comparing code to a utility function

### CODE REVIEW

**Comment by TheLogicMaster** [comment]
I only tested the net functionality, by the way.

**Comment by dezem** [comment]
I tested the other installs, it seems that it works fine. Thank you for your work!

A small fix was needed, if you have no nsp at root dir.
The App crashes if you go to sub dirs.

Fixed with -> https://github.com/dezem/AtmoXL-Titel-Installer/commit/da688d0188578f3fcb389f53ddd01bed1eebe53a

**Comment by TheLogicMaster** [comment]
The same fix is probably needed for the other content sources, as well.

**Comment by dezem** [comment]
@TheLogicMaster big thanks for your contribution for the netinstall, show/hide installed titles and faster scrolling feature. 👍

**Pull request merged**
