### PR TITLE
HTTP Directory Indexing

### PR DESCRIPTION
**Pull request by TheLogicMaster**
Support for Nginx autoindex and Tinfoil style JSON endpoints.

### CODE REVIEW

**Comment by TheLogicMaster** [comment]
Test build:
[AtmoXL-Titel-Installer.zip](https://github.com/dezem/AtmoXL-Titel-Installer/files/7921389/AtmoXL-Titel-Installer.zip)

**Comment by dezem** [comment]
Thats great, thanks for contributing 😉

**Comment by dezem** [comment]
Release is out -> https://github.com/dezem/AtmoXL-Titel-Installer/releases/tag/1.6.3

**Comment by TheLogicMaster** [comment]
Impressive turnaround time.

**Pull request merged**
